name: Build macOS App

# GitHub Actions를 사용한 자동 macOS 빌드
# Windows에서 개발 → GitHub 푸시 → 자동으로 .dmg 생성

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd MacOS
        pip install -r requirements_macos.txt
    
    - name: Build .app and .dmg
      run: |
        cd MacOS
        chmod +x build_all_mac.sh
        ./build_all_mac.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-dmg
        path: MacOS/dist/*.dmg
    
    - name: Create Release (optional)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: MacOS/dist/*.dmg
